@file:Suppress(
    "CanBeVal",
    "FunctionName",
    "KotlinConstantConditions",
    "LocalVariableName",
    "ObsoleteSdkInt",
    "PackageName",
    "PrivatePropertyName",
    "PropertyName",
    "RedundantQualifierName",
    "SameParameterValue",
    "UNUSED_PARAMETER",
    "UseKtxExtensionFunction",
    "unused"
)

package com.flightalert

import android.graphics.Color

data class ThemeColors(
    val map_empty: Int,
    val panel: Int,
    val panel_alt: Int,
    val panel_stroke: Int,
    val control_fill: Int,
    val control_stroke: Int,
    val button_fill: Int,
    val button_stroke: Int,
    val selected_fill_alpha: Int,
    val row_fill_alpha: Int,
    val scrim: Int,
    val text: Int,
    val muted: Int,
    val danger: Int,
    val accent_blue: Int,
    val accent_green: Int,
    val accent_yellow: Int,
    val accent_orange: Int,
    val accent_pink: Int,
    val military: Int,
    val system_bar: Int,
    val street_label_text: Int,
    val street_label_muted: Int,
    val photo_surface: Int,
    val path_shadow: Int
)

data class ThemeStyle(
    val treatment: ThemeTreatment,
    val font_family: String,
    val panel_corner_dp: Float,
    val control_corner_dp: Float,
    val panel_stroke_dp: Float,
    val control_stroke_dp: Float,
    val top_panel_alpha: Int,
    val info_panel_alpha: Int,
    val modal_panel_alpha: Int,
    val control_alpha: Int,
    val divider_alpha: Int,
    val texture_alpha: Int,
    val heading_scale: Float = 1f
)

enum class ThemeTreatment {
    PLAIN,
    GLASS,
    RADAR_GRID,
    DAYLIGHT_CARD,
    STORM_BAND,
    CRT_SCANLINE
}

enum class VisualTheme(
    val display_name: String,
    val short_name: String,
    val colors: ThemeColors,
    val style: ThemeStyle
) {
    COCKPIT(
        display_name = "Cockpit",
        short_name = "Cockpit",
        colors = ThemeColors(
            map_empty = Color.rgb(70, 102, 89),
            panel = Color.rgb(13, 29, 25),
            panel_alt = Color.rgb(18, 31, 29),
            panel_stroke = Color.rgb(39, 65, 55),
            control_fill = Color.rgb(43, 50, 54),
            control_stroke = Color.rgb(230, 235, 225),
            button_fill = Color.rgb(38, 47, 49),
            button_stroke = Color.rgb(59, 68, 70),
            selected_fill_alpha = 55,
            row_fill_alpha = 38,
            scrim = Color.rgb(3, 8, 9),
            text = Color.rgb(232, 241, 229),
            muted = Color.rgb(159, 179, 165),
            danger = Color.rgb(238, 75, 65),
            accent_blue = Color.rgb(105, 205, 244),
            accent_green = Color.rgb(91, 224, 166),
            accent_yellow = Color.rgb(255, 213, 77),
            accent_orange = Color.rgb(255, 144, 82),
            accent_pink = Color.rgb(244, 115, 164),
            military = Color.rgb(156, 165, 163),
            system_bar = Color.rgb(13, 29, 25),
            street_label_text = Color.rgb(20, 42, 37),
            street_label_muted = Color.rgb(56, 83, 75),
            photo_surface = Color.rgb(22, 42, 38),
            path_shadow = Color.rgb(10, 18, 19)
        ),
        style = ThemeStyle(
            treatment = ThemeTreatment.PLAIN,
            font_family = "sans",
            panel_corner_dp = 8f,
            control_corner_dp = 7f,
            panel_stroke_dp = 1f,
            control_stroke_dp = 1.3f,
            top_panel_alpha = 220,
            info_panel_alpha = 236,
            modal_panel_alpha = 255,
            control_alpha = 235,
            divider_alpha = 74,
            texture_alpha = 0
        )
    ),
    TOWER(
        display_name = "Tower Glass",
        short_name = "Tower",
        colors = ThemeColors(
            map_empty = Color.rgb(61, 84, 92),
            panel = Color.rgb(14, 25, 32),
            panel_alt = Color.rgb(20, 35, 44),
            panel_stroke = Color.rgb(53, 88, 101),
            control_fill = Color.rgb(37, 48, 57),
            control_stroke = Color.rgb(209, 226, 230),
            button_fill = Color.rgb(33, 44, 53),
            button_stroke = Color.rgb(79, 99, 110),
            selected_fill_alpha = 58,
            row_fill_alpha = 42,
            scrim = Color.rgb(5, 10, 14),
            text = Color.rgb(238, 246, 244),
            muted = Color.rgb(163, 184, 187),
            danger = Color.rgb(242, 82, 77),
            accent_blue = Color.rgb(125, 206, 255),
            accent_green = Color.rgb(98, 232, 187),
            accent_yellow = Color.rgb(250, 214, 93),
            accent_orange = Color.rgb(255, 158, 92),
            accent_pink = Color.rgb(242, 126, 178),
            military = Color.rgb(172, 181, 183),
            system_bar = Color.rgb(10, 22, 29),
            street_label_text = Color.rgb(18, 40, 48),
            street_label_muted = Color.rgb(55, 80, 87),
            photo_surface = Color.rgb(24, 43, 51),
            path_shadow = Color.rgb(8, 16, 20)
        ),
        style = ThemeStyle(
            treatment = ThemeTreatment.GLASS,
            font_family = "sans-serif-light",
            panel_corner_dp = 14f,
            control_corner_dp = 12f,
            panel_stroke_dp = 1.2f,
            control_stroke_dp = 1.1f,
            top_panel_alpha = 204,
            info_panel_alpha = 224,
            modal_panel_alpha = 255,
            control_alpha = 232,
            divider_alpha = 62,
            texture_alpha = 52,
            heading_scale = 1.04f
        )
    ),
    RADAR(
        display_name = "Radar Scope",
        short_name = "Radar",
        colors = ThemeColors(
            map_empty = Color.rgb(78, 83, 62),
            panel = Color.rgb(24, 25, 18),
            panel_alt = Color.rgb(34, 34, 24),
            panel_stroke = Color.rgb(86, 78, 43),
            control_fill = Color.rgb(49, 48, 37),
            control_stroke = Color.rgb(229, 218, 183),
            button_fill = Color.rgb(43, 42, 32),
            button_stroke = Color.rgb(91, 84, 56),
            selected_fill_alpha = 62,
            row_fill_alpha = 44,
            scrim = Color.rgb(10, 10, 7),
            text = Color.rgb(247, 239, 211),
            muted = Color.rgb(190, 177, 132),
            danger = Color.rgb(255, 91, 74),
            accent_blue = Color.rgb(111, 190, 223),
            accent_green = Color.rgb(119, 224, 153),
            accent_yellow = Color.rgb(255, 198, 76),
            accent_orange = Color.rgb(255, 147, 67),
            accent_pink = Color.rgb(233, 119, 150),
            military = Color.rgb(181, 174, 151),
            system_bar = Color.rgb(24, 25, 18),
            street_label_text = Color.rgb(54, 50, 28),
            street_label_muted = Color.rgb(93, 83, 51),
            photo_surface = Color.rgb(43, 41, 27),
            path_shadow = Color.rgb(18, 15, 8)
        ),
        style = ThemeStyle(
            treatment = ThemeTreatment.RADAR_GRID,
            font_family = "monospace",
            panel_corner_dp = 3f,
            control_corner_dp = 3f,
            panel_stroke_dp = 1f,
            control_stroke_dp = 1f,
            top_panel_alpha = 228,
            info_panel_alpha = 242,
            modal_panel_alpha = 255,
            control_alpha = 238,
            divider_alpha = 96,
            texture_alpha = 44,
            heading_scale = 0.96f
        )
    ),
    DAYLIGHT(
        display_name = "VFR Chart",
        short_name = "Chart",
        colors = ThemeColors(
            map_empty = Color.rgb(117, 150, 153),
            panel = Color.rgb(236, 242, 238),
            panel_alt = Color.rgb(225, 235, 232),
            panel_stroke = Color.rgb(123, 153, 148),
            control_fill = Color.rgb(224, 233, 232),
            control_stroke = Color.rgb(70, 101, 101),
            button_fill = Color.rgb(218, 228, 227),
            button_stroke = Color.rgb(121, 145, 145),
            selected_fill_alpha = 72,
            row_fill_alpha = 68,
            scrim = Color.rgb(20, 30, 33),
            text = Color.rgb(21, 38, 40),
            muted = Color.rgb(80, 102, 99),
            danger = Color.rgb(213, 57, 53),
            accent_blue = Color.rgb(0, 121, 176),
            accent_green = Color.rgb(0, 144, 112),
            accent_yellow = Color.rgb(177, 129, 0),
            accent_orange = Color.rgb(208, 93, 31),
            accent_pink = Color.rgb(205, 70, 128),
            military = Color.rgb(91, 101, 100),
            system_bar = Color.rgb(21, 38, 40),
            street_label_text = Color.rgb(24, 48, 49),
            street_label_muted = Color.rgb(71, 98, 97),
            photo_surface = Color.rgb(207, 222, 220),
            path_shadow = Color.rgb(239, 245, 240)
        ),
        style = ThemeStyle(
            treatment = ThemeTreatment.DAYLIGHT_CARD,
            font_family = "sans-serif",
            panel_corner_dp = 5f,
            control_corner_dp = 4f,
            panel_stroke_dp = 0.8f,
            control_stroke_dp = 1f,
            top_panel_alpha = 236,
            info_panel_alpha = 245,
            modal_panel_alpha = 255,
            control_alpha = 245,
            divider_alpha = 108,
            texture_alpha = 36,
            heading_scale = 0.98f
        )
    ),
    STORM(
        display_name = "Stormscope",
        short_name = "Storm",
        colors = ThemeColors(
            map_empty = Color.rgb(62, 70, 83),
            panel = Color.rgb(18, 21, 30),
            panel_alt = Color.rgb(27, 31, 43),
            panel_stroke = Color.rgb(62, 72, 93),
            control_fill = Color.rgb(42, 46, 57),
            control_stroke = Color.rgb(214, 219, 231),
            button_fill = Color.rgb(37, 41, 52),
            button_stroke = Color.rgb(78, 86, 106),
            selected_fill_alpha = 58,
            row_fill_alpha = 42,
            scrim = Color.rgb(7, 8, 12),
            text = Color.rgb(237, 241, 250),
            muted = Color.rgb(166, 174, 190),
            danger = Color.rgb(255, 84, 88),
            accent_blue = Color.rgb(125, 184, 255),
            accent_green = Color.rgb(93, 222, 175),
            accent_yellow = Color.rgb(245, 205, 83),
            accent_orange = Color.rgb(255, 146, 93),
            accent_pink = Color.rgb(238, 117, 190),
            military = Color.rgb(172, 176, 185),
            system_bar = Color.rgb(16, 19, 27),
            street_label_text = Color.rgb(29, 35, 48),
            street_label_muted = Color.rgb(69, 79, 98),
            photo_surface = Color.rgb(31, 36, 49),
            path_shadow = Color.rgb(8, 10, 16)
        ),
        style = ThemeStyle(
            treatment = ThemeTreatment.STORM_BAND,
            font_family = "sans-serif-medium",
            panel_corner_dp = 2f,
            control_corner_dp = 6f,
            panel_stroke_dp = 1.4f,
            control_stroke_dp = 1.2f,
            top_panel_alpha = 232,
            info_panel_alpha = 244,
            modal_panel_alpha = 252,
            control_alpha = 238,
            divider_alpha = 84,
            texture_alpha = 50,
            heading_scale = 1.02f
        )
    ),
    TERMINAL(
        display_name = "CRT Terminal",
        short_name = "CRT",
        colors = ThemeColors(
            map_empty = Color.rgb(47, 80, 68),
            panel = Color.rgb(5, 24, 17),
            panel_alt = Color.rgb(9, 34, 24),
            panel_stroke = Color.rgb(40, 102, 72),
            control_fill = Color.rgb(25, 48, 39),
            control_stroke = Color.rgb(183, 229, 197),
            button_fill = Color.rgb(19, 43, 33),
            button_stroke = Color.rgb(57, 115, 82),
            selected_fill_alpha = 58,
            row_fill_alpha = 40,
            scrim = Color.rgb(1, 9, 6),
            text = Color.rgb(222, 255, 225),
            muted = Color.rgb(132, 188, 143),
            danger = Color.rgb(255, 80, 69),
            accent_blue = Color.rgb(99, 206, 229),
            accent_green = Color.rgb(91, 246, 132),
            accent_yellow = Color.rgb(229, 235, 92),
            accent_orange = Color.rgb(255, 152, 74),
            accent_pink = Color.rgb(235, 101, 167),
            military = Color.rgb(151, 180, 159),
            system_bar = Color.rgb(5, 24, 17),
            street_label_text = Color.rgb(13, 54, 37),
            street_label_muted = Color.rgb(48, 101, 73),
            photo_surface = Color.rgb(13, 47, 32),
            path_shadow = Color.rgb(3, 14, 8)
        ),
        style = ThemeStyle(
            treatment = ThemeTreatment.CRT_SCANLINE,
            font_family = "monospace",
            panel_corner_dp = 0f,
            control_corner_dp = 2f,
            panel_stroke_dp = 1.1f,
            control_stroke_dp = 1f,
            top_panel_alpha = 238,
            info_panel_alpha = 248,
            modal_panel_alpha = 255,
            control_alpha = 238,
            divider_alpha = 96,
            texture_alpha = 58,
            heading_scale = 0.94f
        )
    );

    companion object {
        val DEFAULT: VisualTheme = COCKPIT

        fun from_name(name: String?): VisualTheme {
            return entries.firstOrNull { it.name == name } ?: DEFAULT
        }
    }
}
